version: '3.3'
services:
  secrets:
    image: wilsonsantosphx/secrets:latest
    container_name: secrets
    ports:
      - "3000:80"
    environment:
      - ConnectionStrings__Default=${ConnectionStrings__Default}
      - JWT__UserKey=${JWT__UserKey}
      - JWT__ShopKey=${JWT__ShopKey}
    restart: always